// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzctdfesrhlvakblpygz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Y3RkZmVzcmhsdmFrYmxweWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDY4MjYsImV4cCI6MjA2NzYyMjgyNn0.5qY7jgWCwardxLZLnwtdEH53HduQjQTgaWom-VSGGQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});